# Generated by Django 5.1.3 on 2026-06-15 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_db_indexes_and_relationships'),
        ('events', '0008_db_indexes_and_relationships'),
        ('payments', '0009_rename_payments_at_attende_2d3e4f_idx_payments_at_attende_cf0285_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['organizer', 'status', 'updated_at'], name='payments_pa_organiz_616b33_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['event', 'status'], name='payments_pa_event_i_06d8c4_idx'),
        ),
    ]
