# Generated by Django 5.1.3 on 2026-06-15 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_db_indexes_and_relationships'),
        ('events', '0008_db_indexes_and_relationships'),
        ('reviews', '0002_eventreview_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventreview',
            index=models.Index(fields=['event', 'created_at'], name='reviews_eve_event_i_879c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreview',
            index=models.Index(fields=['user', 'created_at'], name='reviews_eve_user_id_be30b9_idx'),
        ),
    ]
