# Generated by Django 5.1.3 on 2026-06-15 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_normalize_ticket_type'),
        ('events', '0008_db_indexes_and_relationships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event', 'status'], name='bookings_ti_event_i_03e38f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['attendee', 'status'], name='bookings_ti_attende_7990f2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event', 'billing_email'], name='bookings_ti_event_i_193fea_idx'),
        ),
    ]
